const UPDATE_SEARCH_ACTION = 'UPDATE_SEARCH_STRING'
const SEARCH_USER_ACTION = 'SEARCH_USER_ACTION'
const SEARCH_RESULT_RECEIVED_ACTION = 'SEARCH_RESULT_RECEIVED'
const SEARCH_RESULT_FAILED_ACTION = 'SEARCH_RESULT_FAILED'
const CLEAR_SEARCH_ACTION = 'CLEAR_SEARCH'

const NEXT_RESULT_INIT_ACTION = 'NEXT_RESULT_INIT'

export {
  UPDATE_SEARCH_ACTION,
  SEARCH_USER_ACTION,
  SEARCH_RESULT_RECEIVED_ACTION,
  SEARCH_RESULT_FAILED_ACTION,
  NEXT_RESULT_INIT_ACTION,
  CLEAR_SEARCH_ACTION
}
