const GET_USER_FOLLOWERS_COUNT_ACTION = 'GET_USER_FOLLOWER_COUNT'
const GET_USER_FOLLOWERS_COUNT_SUCCESS_ACTION = 'GET_USER_FOLLOWER_COUNT_SUCCESS'
const GET_USER_FOLLOWERS_COUNT_FAILED_ACTION = 'GET_USER_FOLLOWING_COUNT_FAILED'

const GET_USER_FOLLOWING_COUNT_ACTION = 'GET_USER_FOLLOWING_COUNT'
const GET_USER_FOLLOWING_COUNT_SUCCESS_ACTION = 'GET_USER_FOLLOWING_COUNT_SUCCESS'
const GET_USER_FOLLOWING_COUNT_FAILED_ACTION = 'GET_USER_FOLLOWING_COUNT_FAILED'

const GET_USER_DETAILS_ACTION = 'GET_USER_DETAILS'
const GET_USER_DETAILS_SUCCESS_ACTION = 'GET_USER_DETAILS_SUCCESS'
const GET_USER_DETAILS_FAILED_ACTION = 'GET_USER_DETAILS_FAILED'

export {
  GET_USER_FOLLOWERS_COUNT_ACTION,
  GET_USER_FOLLOWERS_COUNT_SUCCESS_ACTION,
  GET_USER_FOLLOWERS_COUNT_FAILED_ACTION,
  GET_USER_FOLLOWING_COUNT_ACTION,
  GET_USER_FOLLOWING_COUNT_SUCCESS_ACTION,
  GET_USER_FOLLOWING_COUNT_FAILED_ACTION,
  GET_USER_DETAILS_ACTION,
  GET_USER_DETAILS_SUCCESS_ACTION,
  GET_USER_DETAILS_FAILED_ACTION
}
